Repository Bassani-Paulo/Projeto-MC656, pull requests merged in 2024-12, with the labels that each got.

#54 Criando SceneManager como Singleton
  Jogo/project.godot
  Jogo/scenes/SceneManager.tscn
  Jogo/scenes/ui/Main menu.tscn
  Jogo/scripts/SceneManager.gd
  Jogo/scripts/Tartaruga/Jogo da Tartaruga.gd
  Jogo/scripts/ui/main_menu.gd
Labels: Avaliação A4

#46 implementando mecanismo de game over
  Jogo/scenes/Tartaruga/GameOver.tscn
  Jogo/scripts/Tartaruga/GameOver.gd
  Jogo/scripts/Tartaruga/Jogo da Tartaruga.gd
  Jogo/scripts/Tartaruga/LabelLinkTamar.gd
Labels: Jogo da Tartaruga

#58 Adicionando e implementando classe Singleton que gerencia as cenas
  Jogo/project.godot
  Jogo/scenes/SceneManager.tscn
  Jogo/scripts/SceneManager.gd
  Jogo/scripts/Tartaruga/GameOver.gd
  Jogo/scripts/Tartaruga/Global.gd
  Jogo/scripts/Tartaruga/Jogo da Tartaruga.gd
  Jogo/scripts/ui/main_menu.gd
  Jogo/scripts/ui/options.gd
Labels: Avaliação A4

#62 adicionando slider para alterar volume master
  Jogo/Audio/Awakening Nature.mp3
  Jogo/Audio/Awakening Nature.mp3.import
  Jogo/default_bus_layout.tres
  Jogo/scenes/ui/Main menu.tscn
  Jogo/scenes/ui/Options.tscn
  Jogo/scripts/ui/options.gd
Labels: Jogo da Tartaruga

#63 alteracoes menu
  Jogo/assets/sprites/menu abelha.jpg
  Jogo/assets/sprites/menu abelha.jpg.import
  Jogo/assets/sprites/menu tartaruga.png
  Jogo/assets/sprites/menu tartaruga.png.import
  Jogo/assets/sprites/menu_jogo_reciclagem.jpg
  Jogo/assets/sprites/menu_jogo_reciclagem.jpg.import
  Jogo/fonts/kirifont/KiriFont.otf
  Jogo/fonts/kirifont/KiriFont.otf.import
  Jogo/fonts/kirifont/KiriFont.ttf
  Jogo/fonts/kirifont/KiriFont.ttf.import
  Jogo/fonts/kirifont/Kirifont.tres
  Jogo/fonts/kirifont/OFL.txt
  Jogo/scenes/ui/Main menu.tscn
  Jogo/scenes/ui/Options.tscn
  Jogo/scenes/ui/botao_jogo_reciclagem.gd
  Jogo/scripts/ui/botao_jogo_abelha.gd
  Jogo/scripts/ui/botao_jogo_tartaruga.gd
Labels: UI

#64 Adicionando Testes de valor limite
  Jogo/scenes/ui/Main menu.tscn
  Jogo/scenes/ui/Options.tscn
  Jogo/scripts/Tartaruga/lixo.gd
  Jogo/scripts/Tartaruga/timer_alga.gd
  Jogo/scripts/Tartaruga/timer_canudo.gd
  Jogo/tests/test_limit_alga.gd
  Jogo/tests/test_limit_canudo.gd
  Jogo/tests/test_limit_position_x.gd
  Jogo/tests/test_limit_position_y.gd
  Jogo/tests/test_obstacles.gd
Labels: AvaliaçãoA5
